export const ROUTES = {
  HOME: "/",
  PHILOSOPHERS: "/philosophers",
  PHILOSOPHER_DETAILS: "/philosophers/:id",
  ARTICLS: "/articles",
  ARTICLE_DETAILS: "/articles/:id",
  ADD_ARTICLE: "/articles/add",
  TIMELINE: "/timeline",
  LOGIN: "/login",
  SIGNUP: "/signup",
  RESET_PASSWORD: "/reset-password",
  PROFILE: "/profile/:id",
  SCHOOLS: "/schools",
  SCHOOL_DETAILS: "/schools/:id",
  BOOKS: "/books",
  BOOK_DETAILS: "/books/:id",
};
