-- =============================================================================
-- Philos - PostgreSQL Database Schema (Neon)
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- -----------------------------------------------------------------------------
-- 1. Users & Authentication
-- -----------------------------------------------------------------------------

CREATE TABLE users (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email           VARCHAR(320) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    email_confirmed BOOLEAN      NOT NULL DEFAULT FALSE,
    role            VARCHAR(20)  NOT NULL DEFAULT 'user',
    phone           VARCHAR(20)  NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('user', 'admin'))
);

CREATE TABLE profiles (
    id          UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    username    VARCHAR(50)  NOT NULL,
    full_name   VARCHAR(200) NULL,
    bio         TEXT         NULL,
    avatar_url  VARCHAR(500) NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_profiles_username UNIQUE (username)
);

-- later
-- CREATE TABLE password_reset_tokens ( ... );
-- CREATE TABLE refresh_tokens ( ... );

-- -----------------------------------------------------------------------------
-- 2. Philosophers
-- -----------------------------------------------------------------------------

CREATE TABLE philosophers (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_en              VARCHAR(200) NOT NULL,
    name_ar              VARCHAR(200) NOT NULL,
    birth                INTEGER      NULL,
    death                INTEGER      NULL,
    era_en               VARCHAR(100) NULL,
    era_ar               VARCHAR(100) NULL,
    era_slug             VARCHAR(50)  NULL,  -- ancient, medieval, earlyModern, modern, contemporary
    nationality_en       VARCHAR(100) NULL,
    nationality_ar       VARCHAR(100) NULL,
    quote_en             VARCHAR(500) NULL,
    quote_ar             VARCHAR(500) NULL,
    short_description_en TEXT         NULL,
    short_description_ar TEXT         NULL,
    image_url            VARCHAR(500) NULL,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_philosophers_era_slug ON philosophers(era_slug);
CREATE INDEX ix_philosophers_name_en  ON philosophers(name_en);
CREATE INDEX ix_philosophers_name_ar  ON philosophers(name_ar);

-- -----------------------------------------------------------------------------
-- 3. Philosopher Bios
-- -----------------------------------------------------------------------------

CREATE TABLE philosopher_bios (
    philosopher_id      INTEGER PRIMARY KEY REFERENCES philosophers(id) ON DELETE CASCADE,
    intro_en            TEXT NULL,
    intro_ar            TEXT NULL,
    early_life_en       TEXT NULL,
    early_life_ar       TEXT NULL,
    education_en        TEXT NULL,
    education_ar        TEXT NULL,
    books_en            TEXT NULL,
    books_ar            TEXT NULL,
    metaphysics_en      TEXT NULL,
    metaphysics_ar      TEXT NULL,
    epistemology_en     TEXT NULL,
    epistemology_ar     TEXT NULL,
    ethics_en           TEXT NULL,
    ethics_ar           TEXT NULL,
    politics_en         TEXT NULL,
    politics_ar         TEXT NULL,
    influence_legacy_en TEXT NULL,
    influence_legacy_ar TEXT NULL,
    personal_life_en    TEXT NULL,
    personal_life_ar    TEXT NULL,
    death_section_en    TEXT NULL,
    death_section_ar    TEXT NULL,
    further_reading_en  TEXT NULL,
    further_reading_ar  TEXT NULL,
    references_en       TEXT NULL,
    references_ar       TEXT NULL
);

-- -----------------------------------------------------------------------------
-- 4. Articles
-- -----------------------------------------------------------------------------

CREATE TABLE articles (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title      VARCHAR(300) NOT NULL,
    subtitle   VARCHAR(500) NOT NULL,
    content    TEXT         NOT NULL,
    category   VARCHAR(100) NOT NULL,
    state      VARCHAR(20)  NOT NULL DEFAULT 'draft',
    author_id  UUID         NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_articles_state CHECK (state IN ('draft', 'published'))
);

CREATE INDEX ix_articles_state      ON articles(state);
CREATE INDEX ix_articles_author_id  ON articles(author_id);
CREATE INDEX ix_articles_created_at ON articles(created_at DESC);

-- -----------------------------------------------------------------------------
-- 5. Article Reactions
-- -----------------------------------------------------------------------------

CREATE TABLE article_reactions (
    article_id UUID        NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    user_id    UUID        NOT NULL REFERENCES users(id),
    reaction   VARCHAR(10) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_article_reactions PRIMARY KEY (article_id, user_id),
    CONSTRAINT ck_article_reactions_reaction CHECK (reaction IN ('like', 'dislike'))
);

CREATE VIEW article_reaction_counts AS
SELECT
    a.id AS article_id,
    COALESCE(SUM(CASE WHEN r.reaction = 'like'    THEN 1 ELSE 0 END), 0)::INTEGER AS likes,
    COALESCE(SUM(CASE WHEN r.reaction = 'dislike' THEN 1 ELSE 0 END), 0)::INTEGER AS dislikes
FROM articles a
LEFT JOIN article_reactions r ON r.article_id = a.id
GROUP BY a.id;

-- -----------------------------------------------------------------------------
-- 6. Comments (nested via parent_id; depth 0..5)
-- -----------------------------------------------------------------------------

CREATE TABLE comments (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    article_id UUID        NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    user_id    UUID        NOT NULL REFERENCES users(id),
    parent_id  UUID        NULL REFERENCES comments(id),
    content    TEXT        NOT NULL,
    depth      INTEGER     NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_comments_depth CHECK (depth >= 0 AND depth <= 5)
);

CREATE INDEX ix_comments_article_id ON comments(article_id, created_at DESC);
CREATE INDEX ix_comments_parent_id  ON comments(parent_id, created_at ASC);

-- -----------------------------------------------------------------------------
-- 6b. Comment Reactions
-- -----------------------------------------------------------------------------

CREATE TABLE comment_reactions (
    comment_id UUID        NOT NULL REFERENCES comments(id) ON DELETE CASCADE,
    user_id    UUID        NOT NULL REFERENCES users(id),
    reaction   VARCHAR(10) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_comment_reactions PRIMARY KEY (comment_id, user_id),
    CONSTRAINT ck_comment_reactions_reaction CHECK (reaction IN ('like', 'dislike'))
);

CREATE VIEW comment_reaction_counts AS
SELECT
    c.id AS comment_id,
    COALESCE(SUM(CASE WHEN r.reaction = 'like'    THEN 1 ELSE 0 END), 0)::INTEGER AS likes,
    COALESCE(SUM(CASE WHEN r.reaction = 'dislike' THEN 1 ELSE 0 END), 0)::INTEGER AS dislikes
FROM comments c
LEFT JOIN comment_reactions r ON r.comment_id = c.id
GROUP BY c.id;

-- -----------------------------------------------------------------------------
-- 7. Article Bookmarks
-- -----------------------------------------------------------------------------

CREATE TABLE article_bookmarks (
    user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    article_id UUID        NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_article_bookmarks PRIMARY KEY (user_id, article_id)
);

-- -----------------------------------------------------------------------------
-- 8. Schools
-- -----------------------------------------------------------------------------

CREATE TABLE schools (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_en         VARCHAR(200) NOT NULL,
    name_ar         VARCHAR(200) NOT NULL,
    slug            VARCHAR(100) NOT NULL,
    description_en  TEXT         NULL,
    description_ar  TEXT         NULL,
    founded_period  VARCHAR(100) NULL,
    image_url       VARCHAR(500) NULL,
    CONSTRAINT uq_schools_slug UNIQUE (slug)
);

CREATE TABLE philosopher_schools (
    philosopher_id INTEGER NOT NULL REFERENCES philosophers(id) ON DELETE CASCADE,
    school_id      INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    CONSTRAINT pk_philosopher_schools PRIMARY KEY (philosopher_id, school_id)
);

-- -----------------------------------------------------------------------------
-- 9. Books
-- -----------------------------------------------------------------------------

CREATE TABLE books (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_en         VARCHAR(300) NOT NULL,
    title_ar         VARCHAR(300) NOT NULL,
    author_en        VARCHAR(200) NULL,
    author_ar        VARCHAR(200) NULL,
    description_en   TEXT         NULL,
    description_ar   TEXT         NULL,
    cover_image_url  VARCHAR(500) NULL,
    published_year   INTEGER      NULL
);

CREATE TABLE user_book_lists (
    user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    book_id    INTEGER     NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    list_type  VARCHAR(20) NOT NULL,
    added_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_user_book_lists PRIMARY KEY (user_id, book_id, list_type),
    CONSTRAINT ck_user_book_lists_list_type CHECK (list_type IN ('to_read', 'reading', 'read', 'favorite'))
);

-- -----------------------------------------------------------------------------
-- 10. Timeline — deferred to a later phase
-- -----------------------------------------------------------------------------

-- CREATE TABLE timeline_events (
--     id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     year            INTEGER      NOT NULL,
--     title_en        VARCHAR(300) NOT NULL,
--     title_ar        VARCHAR(300) NOT NULL,
--     description_en  TEXT         NULL,
--     description_ar  TEXT         NULL,
--     philosopher_id  INTEGER      NULL REFERENCES philosophers(id),
--     school_id       INTEGER      NULL REFERENCES schools(id)
-- );
-- CREATE INDEX ix_timeline_events_year ON timeline_events(year);

-- -----------------------------------------------------------------------------
-- Triggers
-- -----------------------------------------------------------------------------

-- Auto-create profile when a user signs up
CREATE OR REPLACE FUNCTION trg_users_after_insert_create_profile()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO profiles (id, username)
    VALUES (
        NEW.id,
        LEFT(REPLACE(NEW.email, '@', '_'), 50)
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_users_after_insert
AFTER INSERT ON users
FOR EACH ROW
EXECUTE FUNCTION trg_users_after_insert_create_profile();

-- Note: article/book count sync triggers removed — counts are derived via COUNT/views
-- from articles and user_book_lists (no denormalized counters on profiles).
