import React from 'react';
import './Articles.scss';
import { Button } from '@mui/material';
import { supabase } from '../../supabaseClient';
import { PhilosophersData } from '../philosophers/data/PhilosophersData';
import ArticlesCard from './components/ArticlesCard';

const Articles: React.FC = () => {
  const philosophers = [
    {
      "name_en": "Socrates",
      "name_ar": "سقراط",
      "school_en": "Classical Greek Philosophy",
      "school_ar": "الفلسفة اليونانية الكلاسيكية",
      "era_en": "Classical antiquity",
      "era_ar": "العصور الكلاسيكية القديمة",
      "image": "https://upload.wikimedia.org/wikipedia/commons/a/a2/Socrates_Glyptothek_Munich_309.jpg",
      "short_description_en": "A classical Greek philosopher credited as one of the founders of Western philosophy.",
      "short_description_ar": "فيلسوف يوناني كلاسيكي يُنسب إليه الفضل كأحد مؤسسي الفلسفة الغربية.",
      "birth": "-470",
      "death": "-399",
      "nationality_en": "Athenian",
      "nationality_ar": "أثيني",
      "long_article_en": "Socrates was a pivotal figure in ancient Greek philosophy. He is known for his Socratic method of inquiry, a form of cooperative argumentative dialogue between individuals, based on asking and answering questions to stimulate critical thinking and to illuminate ideas. He never wrote down his philosophical thoughts; our knowledge of him comes primarily from the writings of his students, including Plato and Xenophon. He was executed by the Athenian state after being convicted of corrupting the youth and impiety, a story that became a cornerstone of Western philosophical ethics.",
      "long_article_ar": "كان سقراط شخصية محورية في الفلسفة اليونانية القديمة. يُعرف بطريقته السقراطية في البحث، وهي شكل من أشكال الحوار الجدلي التعاوني بين الأفراد، القائم على طرح الأسئلة والإجابة عليها لتحفيز التفكير النقدي وتوضيح الأفكار. لم يكتب أبدًا أفكاره الفلسفية؛ معرفتنا به تأتي في المقام الأول من كتابات تلاميذه، بما في ذلك أفلاطون وزينوفون. تم إعدامه من قبل الدولة الأثينية بعد إدانته بإفساد الشباب والزندقة، وهي قصة أصبحت حجر الزاوية في الأخلاق الفلسفية الغربية.",
      "philosophical_impact_en": "His emphasis on virtue, knowledge, and self-examination profoundly influenced Western philosophy. His student Plato and Plato's student Aristotle are the three central figures in ancient philosophy. The Socratic method is still a fundamental tool in education and legal practice.",
      "philosophical_impact_ar": "أثر تركيزه على الفضيلة والمعرفة وفحص الذات بعمق في الفلسفة الغربية. تلميذه أفلاطون وتلميذ أفلاطون أرسطو هم الشخصيات المركزية الثلاث في الفلسفة القديمة. لا تزال الطريقة السقراطية أداة أساسية في التعليم والممارسة القانونية."
    },
    {
      "name_en": "Plato",
      "name_ar": "أفلاطون",
      "school_en": "Platonism",
      "school_ar": "الأفلاطونية",
      "era_en": "Classical antiquity",
      "era_ar": "العصور الكلاسيكية القديمة",
      "image": "https://upload.wikimedia.org/wikipedia/commons/8/88/Plato_Silanion_Musei_Capitolini_MC1377.jpg",
      "short_description_en": "An Athenian philosopher, student of Socrates, and founder of the Academy in Athens.",
      "short_description_ar": "فيلسوف أثيني، تلميذ سقراط، ومؤسس الأكاديمية في أثينا.",
      "birth": "-428/-427",
      "death": "-348/-347",
      "nationality_en": "Athenian",
      "nationality_ar": "أثيني",
      "long_article_en": "Plato's philosophy is one of the most influential in the Western tradition. His Theory of Forms posits that the physical world is not as real as the abstract, eternal Forms. His most famous work, 'The Republic,' outlines his vision for a just city-state ruled by 'philosopher kings.' His writings, mostly in dialogue form, cover a wide range of topics, including ethics, politics, metaphysics, and aesthetics.",
      "long_article_ar": "فلسفة أفلاطون هي واحدة من أكثر الفلسفات تأثيرًا في التقليد الغربي. نظرية الأشكال التي وضعها تفترض أن العالم المادي ليس حقيقيًا مثل الأشكال المجردة والأبدية. أشهر أعماله، 'الجمهورية'، تحدد رؤيته لمدينة-دولة عادلة يحكمها 'الملوك الفلاسفة'. تغطي كتاباته، التي تكون في الغالب على شكل حوار، مجموعة واسعة من المواضيع، بما في ذلك الأخلاق والسياسة والميتافيزيقا والجماليات.",
      "philosophical_impact_en": "Plato's ideas laid the groundwork for Western philosophy and religion. His dualism of mind and body, his theory of knowledge, and his political philosophy have been central to philosophical debate for over two millennia.",
      "philosophical_impact_ar": "أرست أفكار أفلاطون الأساس للفلسفة والدين الغربيين. ثنائيته للعقل والجسد، ونظريته في المعرفة، وفلسفته السياسية كانت محورية في النقاش الفلسفي لأكثر من ألفي عام."
    },
    {
      "name_en": "Aristotle",
      "name_ar": "أرسطو",
      "school_en": "Peripatetic school, Aristotelianism",
      "school_ar": "المدرسة المشائية، الأرسطية",
      "era_en": "Classical antiquity",
      "era_ar": "العصور الكلاسيكية القديمة",
      "image": "https://upload.wikimedia.org/wikipedia/commons/a/ae/Aristotle_Altemps_Inv8575.jpg",
      "short_description_en": "A Greek philosopher and polymath, student of Plato, and teacher of Alexander the Great.",
      "short_description_ar": "فيلسوف يوناني وموسوعي، تلميذ أفلاطون، ومعلم الإسكندر الأكبر.",
      "birth": "-384",
      "death": "-322",
      "nationality_en": "Macedonian (Stagira)",
      "nationality_ar": "مقدوني (ستيغييرا)",
      "long_article_en": "Aristotle's writings cover a vast range of subjects, including physics, biology, zoology, metaphysics, logic, ethics, aesthetics, poetry, theater, music, rhetoric, psychology, and politics. He established the Lyceum in Athens and is considered one of the most influential figures in the history of Western thought. His empirical approach and systematic classification of knowledge set a new standard for scientific inquiry.",
      "long_article_ar": "تغطي كتابات أرسطو مجموعة واسعة من المواضيع، بما في ذلك الفيزياء، وعلم الأحياء، وعلم الحيوان، والميتافيزيقا، والمنطق، والأخلاق، والجماليات، والشعر، والمسرح، والموسيقى، والبلاغة، وعلم النفس، والسياسة. أسس الليسيوم في أثينا ويعتبر أحد أكثر الشخصيات تأثيرًا في تاريخ الفكر الغربي. منهجه التجريبي وتصنيفه المنهجي للمعرفة وضعا معيارًا جديدًا للبحث العلمي.",
      "philosophical_impact_en": "Aristotle's philosophy formed the foundation of much of Western thought. His logic system was dominant for centuries, and his concepts of virtue, teleology, and the 'golden mean' are still widely discussed. He also had a profound influence on Islamic and Christian theology and philosophy.",
      "philosophical_impact_ar": "شكلت فلسفة أرسطو أساسًا للكثير من الفكر الغربي. كان نظامه المنطقي مهيمنًا لقرون، ولا تزال مفاهيمه عن الفضيلة والغائية و'الوسط الذهبي' تُناقش على نطاق واسع. كان له أيضًا تأثير عميق على اللاهوت والفلسفة الإسلامية والمسيحية."
    },
    {
      "name_en": "Confucius",
      "name_ar": "كونفوشيوس",
      "school_en": "Confucianism",
      "school_ar": "الكونفوشيوسية",
      "era_en": "Classical antiquity",
      "era_ar": "العصور الكلاسيكية القديمة",
      "image": "https://upload.wikimedia.org/wikipedia/commons/7/77/Confucius_c.1770.jpg",
      "short_description_en": "A Chinese philosopher and politician whose philosophy became the basis for Confucianism.",
      "short_description_ar": "فيلسوف وسياسي صيني أصبحت فلسفته أساسًا للكونفوشيوسية.",
      "birth": "-551",
      "death": "-479",
      "nationality_en": "Chinese",
      "nationality_ar": "صيني",
      "long_article_en": "Confucius's philosophy emphasized personal and governmental morality, correctness of social relationships, justice, kindness, and sincerity. He believed in the importance of education and self-cultivation. His teachings, preserved in the 'Analects,' focus on the concept of 'ren' (humaneness) and 'li' (ritual and propriety).",
      "long_article_ar": "أكدت فلسفة كونفوشيوس على الأخلاق الشخصية والحكومية، وصحة العلاقات الاجتماعية، والعدالة، واللطف، والإخلاص. آمن بأهمية التعليم وتنمية الذات. تركز تعاليمه، المحفوظة في 'مختارات كونفوشيوس'، على مفهوم 'الرن' (الإنسانية) و'اللي' (الطقوس واللياقة).",
      "philosophical_impact_en": "Confucianism has had a profound influence on Chinese and East Asian culture, politics, and social thought for over two millennia. It shaped the civil service examination system and remains a key component of East Asian values.",
      "philosophical_impact_ar": "كان للكونفوشيوسية تأثير عميق على الثقافة والسياسة والفكر الاجتماعي الصيني والشرق آسيوي لأكثر من ألفي عام. لقد شكلت نظام الامتحانات المدنية ولا تزال مكونًا رئيسيًا للقيم في شرق آسيا."
    },
    {
      "name_en": "Thomas Aquinas",
      "name_ar": "توما الأكويني",
      "school_en": "Scholasticism, Thomism",
      "school_ar": "المدرسية، التوماوية",
      "era_en": "Medieval period",
      "era_ar": "العصور الوسطى",
      "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Carlo_Crivelli_002.jpg",
      "short_description_en": "An Italian Dominican friar, Catholic priest, and Doctor of the Church, known for his synthesis of Aristotelian philosophy and Christian theology.",
      "short_description_ar": "راهب دومينيكي إيطالي، كاهن كاثوليكي، ومُعلّم الكنيسة، معروف بتوليفه للفلسفة الأرسطية واللاهوت المسيحي.",
      "birth": "1225",
      "death": "1274",
      "nationality_en": "Italian",
      "nationality_ar": "إيطالي",
      "long_article_en": "Thomas Aquinas was a towering figure of scholasticism. His most famous works, the 'Summa Theologica' and the 'Summa contra Gentiles,' systematically laid out his arguments for the existence of God and his views on morality, law, and salvation. He argued that reason and faith could be reconciled and that both were paths to truth.",
      "long_article_ar": "كان توما الأكويني شخصية بارزة في الفلسفة المدرسية. أعماله الأكثر شهرة، 'الخلاصة اللاهوتية' و'الخلاصة ضد الوثنيين'، طرحت بشكل منهجي حججه لوجود الله ووجهات نظره حول الأخلاق والقانون والخلاص. جادل بأن العقل والإيمان يمكن التوفيق بينهما وأن كلاهما طريق للوصول إلى الحقيقة.",
      "philosophical_impact_en": "Aquinas's philosophy became the official philosophy of the Catholic Church. His works on natural law, ethics, and metaphysics are still central to Catholic theology and have had a profound impact on Western philosophy.",
      "philosophical_impact_ar": "أصبحت فلسفة الأكويني الفلسفة الرسمية للكنيسة الكاثوليكية. ولا تزال أعماله حول القانون الطبيعي والأخلاق والميتافيزيقا محورية في اللاهوت الكاثوليكي وكان لها تأثير عميق على الفلسفة الغربية."
    },
    {
      "name_en": "René Descartes",
      "name_ar": "رينيه ديكارت",
      "school_en": "Rationalism",
      "school_ar": "العقلانية",
      "era_en": "Early modern period",
      "era_ar": "العصر الحديث المبكر",
      "image": "https://upload.wikimedia.org/wikipedia/commons/7/7b/Frans_Hals_-_Portret_van_Ren%C3%A9_Descartes.jpg",
      "short_description_en": "A French philosopher, mathematician, and scientist, considered the 'Father of Modern Philosophy.'",
      "short_description_ar": "فيلسوف ورياضياتي وعالم فرنسي، يُعتبر 'أبو الفلسفة الحديثة'.",
      "birth": "1596",
      "death": "1650",
      "nationality_en": "French",
      "nationality_ar": "فرنسي",
      "long_article_en": "Descartes is famous for his statement 'Cogito, ergo sum' ('I think, therefore I am'), which he used to establish a foundation of certainty in a world of doubt. He is a key figure in the Scientific Revolution and laid the groundwork for rationalism. His works include 'Meditations on First Philosophy' and 'Discourse on the Method.'",
      "long_article_ar": "يُشتهر ديكارت بعبارته 'أنا أفكر، إذن أنا موجود' ('Cogito, ergo sum')، التي استخدمها لتأسيس أساس من اليقين في عالم من الشك. هو شخصية رئيسية في الثورة العلمية وأرسى الأساس للعقلانية. تشمل أعماله 'تأملات في الفلسفة الأولى' و'مقال في المنهج'.",
      "philosophical_impact_en": "Descartes's dualism of mind and body, his emphasis on reason as the primary source of knowledge, and his method of systematic doubt had a profound and lasting impact on philosophy and science, shaping the course of Western thought.",
      "philosophical_impact_ar": "كانت لثنائية ديكارت للعقل والجسد، وتركيزه على العقل كمصدر أساسي للمعرفة، ومنهجه في الشك المنهجي تأثير عميق ودائم على الفلسفة والعلوم، وشكلت مسار الفكر الغربي."
    },
    {
      "name_en": "John Locke",
      "name_ar": "جون لوك",
      "school_en": "Empiricism",
      "school_ar": "التجريبية",
      "era_en": "Early modern period",
      "era_ar": "العصر الحديث المبكر",
      "image": "https://upload.wikimedia.org/wikipedia/commons/b/b8/John_Locke.jpg",
      "short_description_en": "An English philosopher and physician, widely regarded as one of the most influential of Enlightenment thinkers and known as the 'Father of Liberalism.'",
      "short_description_ar": "فيلسوف وطبيب إنجليزي، يُعتبر على نطاق واسع أحد أكثر مفكري التنوير تأثيرًا ويُعرف باسم 'أبو الليبرالية'.",
      "birth": "1632",
      "death": "1704",
      "nationality_en": "English",
      "nationality_ar": "إنجليزي",
      "long_article_en": "Locke's 'An Essay Concerning Human Understanding' is a cornerstone of empiricism, arguing that the mind is a 'tabula rasa' (blank slate) at birth and that all knowledge comes from experience. In his 'Two Treatises of Government,' he argued for the natural rights to life, liberty, and property, and for government by the consent of the governed.",
      "long_article_ar": "يُعتبر 'مقال عن الفهم الإنساني' للوك حجر الزاوية في التجريبية، حيث يجادل بأن العقل هو 'لوح فارغ' (tabula rasa) عند الولادة وأن كل المعرفة تأتي من التجربة. في 'رسالتان في الحكم'، جادل بالحقوق الطبيعية في الحياة والحرية والملكية، والحكم بموافقة المحكومين.",
      "philosophical_impact_en": "Locke's political philosophy profoundly influenced the American and French Revolutions and the development of liberal democracy. His ideas on human rights, the social contract, and the separation of powers are fundamental to modern political thought.",
      "philosophical_impact_ar": "أثرت فلسفة لوك السياسية بعمق على الثورتين الأمريكية والفرنسية وتطور الديمقراطية الليبرالية. أفكاره حول حقوق الإنسان، والعقد الاجتماعي، وفصل السلطات هي أساسية للفكر السياسي الحديث."
    },
    {
      "name_en": "David Hume",
      "name_ar": "ديفيد هيوم",
      "school_en": "Empiricism, Skepticism",
      "school_ar": "التجريبية، الشكوكية",
      "era_en": "Early modern period",
      "era_ar": "العصر الحديث المبكر",
      "image": "https://upload.wikimedia.org/wikipedia/commons/d/de/Allan_Ramsay_-_David_Hume%2C_1711_-_1776_-_Google_Art_Project.jpg",
      "short_description_en": "A Scottish Enlightenment philosopher, historian, economist, librarian, and essayist.",
      "short_description_ar": "فيلسوف ومؤرخ واقتصادي وأمين مكتبة ومقالي من عصر التنوير الاسكتلندي.",
      "birth": "1711",
      "death": "1776",
      "nationality_en": "Scottish",
      "nationality_ar": "اسكتلندي",
      "long_article_en": "Hume is best known for his philosophical empiricism and skepticism. In his work 'A Treatise of Human Nature,' he argued that all knowledge is derived from sense experience and that causal relationships are based on custom or habit, not on necessary connections. He was a radical skeptic, questioning the existence of God, the self, and causality.",
      "long_article_ar": "يُعرف هيوم بشكل أساسي بتجريبيته وشكيته الفلسفية. في عمله 'رسالة في الطبيعة البشرية'، جادل بأن كل المعرفة مستمدة من الخبرة الحسية وأن العلاقات السببية تستند إلى العادة أو الممارسة، وليس على روابط ضرورية. كان متشككًا جذريًا، حيث شكك في وجود الله والذات والسببية.",
      "philosophical_impact_en": "Hume's skepticism was a major challenge to both rationalism and empiricism. His critique of causality and his analysis of the problem of induction were a profound influence on Immanuel Kant and the subsequent development of philosophy.",
      "philosophical_impact_ar": "كانت شكوكية هيوم تحديًا كبيرًا لكل من العقلانية والتجريبية. كان نقده للسببية وتحليله لمشكلة الاستقراء لهما تأثير عميق على إيمانويل كانط والتطور اللاحق للفلسفة."
    },
    {
      "name_en": "Immanuel Kant",
      "name_ar": "إيمانويل كانط",
      "school_en": "Critical philosophy",
      "school_ar": "الفلسفة النقدية",
      "era_en": "Early modern period",
      "era_ar": "العصر الحديث المبكر",
      "image": "https://upload.wikimedia.org/wikipedia/commons/3/36/Kant_gemaelde_1.jpg",
      "short_description_en": "A German philosopher who is a central figure in modern philosophy.",
      "short_description_ar": "فيلسوف ألماني وهو شخصية محورية في الفلسفة الحديثة.",
      "birth": "1724",
      "death": "1804",
      "nationality_en": "German",
      "nationality_ar": "ألماني",
      "long_article_en": "Kant's work, especially 'Critique of Pure Reason,' sought to synthesize rationalism and empiricism. He argued that our understanding of the world is shaped by both sensory experience and innate mental categories ('a priori' concepts). His moral philosophy is based on the Categorical Imperative, a universal and unconditional moral law.",
      "long_article_ar": "سعى عمل كانط، وخاصة 'نقد العقل الخالص'، إلى توليف العقلانية والتجريبية. جادل بأن فهمنا للعالم يتشكل من خلال كل من الخبرة الحسية والفئات العقلية الفطرية ('المفاهيم القبلية'). تستند فلسفته الأخلاقية إلى الأمر القطعي، وهو قانون أخلاقي عالمي وغير مشروط.",
      "philosophical_impact_en": "Kant's 'Copernican Revolution' in philosophy fundamentally changed the way people understood the relationship between the mind and reality. His ideas on ethics, epistemology, and aesthetics have been foundational to much of subsequent philosophy.",
      "philosophical_impact_ar": "غيرت 'ثورة كانط الكوبرنيكية' في الفلسفة بشكل أساسي الطريقة التي فهم بها الناس العلاقة بين العقل والواقع. كانت أفكاره حول الأخلاق ونظرية المعرفة والجماليات أساسية للكثير من الفلسفة اللاحقة."
    },
    {
      "name_en": "Jean-Jacques Rousseau",
      "name_ar": "جان جاك روسو",
      "school_en": "Social contract theory",
      "school_ar": "نظرية العقد الاجتماعي",
      "era_en": "Early modern period",
      "era_ar": "العصر الحديث المبكر",
      "image": "https://upload.wikimedia.org/wikipedia/commons/b/b8/Jean-Jacques_Rousseau_%28painted_portrait%29.jpg",
      "short_description_en": "A Genevan philosopher, writer, and composer of the 18th century.",
      "short_description_ar": "فيلسوف وكاتب وملحن من جنيف من القرن الثامن عشر.",
      "birth": "1712",
      "death": "1778",
      "nationality_en": "Genevan (Swiss)",
      "nationality_ar": "جنيفي (سويسري)",
      "long_article_en": "Rousseau's political philosophy, as outlined in 'The Social Contract,' argued that a legitimate political authority must be based on a social contract between citizens for the sake of the 'general will.' He believed that humans are inherently good but are corrupted by society. His work 'Emile, or On Education' laid out his ideas for a new system of education.",
      "long_article_ar": "جادلت فلسفة روسو السياسية، كما ورد في 'العقد الاجتماعي'، بأن السلطة السياسية الشرعية يجب أن تستند إلى عقد اجتماعي بين المواطنين من أجل 'الإرادة العامة'. آمن بأن البشر خيرون بطبيعتهم ولكن يفسدهم المجتمع. عمله 'إميل، أو في التربية' وضع أفكاره لنظام تعليمي جديد.",
      "philosophical_impact_en": "Rousseau's ideas on the social contract and the general will were highly influential on the French Revolution and the development of modern political and educational thought. He is also considered a key figure in the transition from the Enlightenment to Romanticism.",
      "philosophical_impact_ar": "كانت أفكار روسو حول العقد الاجتماعي والإرادة العامة مؤثرة للغاية في الثورة الفرنسية وتطور الفكر السياسي والتربوي الحديث. يعتبر أيضًا شخصية رئيسية في الانتقال من التنوير إلى الرومانسية."
    },
    {
      "name_en": "Friedrich Nietzsche",
      "name_ar": "فريدريك نيتشه",
      "school_en": "Nietzschean philosophy, Existentialism",
      "school_ar": "الفلسفة النيتشوية، الوجودية",
      "era_en": "19th century",
      "era_ar": "القرن التاسع عشر",
      "image": "https://upload.wikimedia.org/wikipedia/commons/e/e4/Friedrich_Nietzsche_c_1870s.jpg",
      "short_description_en": "A German philosopher, cultural critic, composer, poet, and philologist.",
      "short_description_ar": "فيلسوف ألماني، وناقد ثقافي، وملحن، وشاعر، وعالم لغوي.",
      "birth": "1844",
      "death": "1900",
      "nationality_en": "German",
      "nationality_ar": "ألماني",
      "long_article_en": "Nietzsche's work is characterized by its radical critique of truth, morality, and religion. He famously declared 'God is dead' and explored the implications of this for Western culture. Key concepts in his philosophy include the 'will to power,' the 'Übermensch' (superman), and the idea of 'eternal recurrence.'",
      "long_article_ar": "يتميز عمل نيتشه بنقده الراديكالي للحقيقة والأخلاق والدين. أعلن عبارته الشهيرة 'مات الإله' واستكشف تداعيات ذلك على الثقافة الغربية. تشمل المفاهيم الرئيسية في فلسفته 'إرادة القوة'، و'الإنسان السوبر' (Übermensch)، وفكرة 'العود الأبدي'.",
      "philosophical_impact_en": "Nietzsche's philosophy has had a profound influence on existentialism, postmodernism, and psychoanalysis. His critique of traditional values and his focus on the individual's will to create meaning have been highly influential in 20th and 21st-century thought.",
      "philosophical_impact_ar": "كان لفلسفة نيتشه تأثير عميق على الوجودية وما بعد الحداثة والتحليل النفسي. كان نقده للقيم التقليدية وتركيزه على إرادة الفرد لخلق المعنى مؤثرًا للغاية في فكر القرنين العشرين والحادي والعشرين."
    },
    {
      "name_en": "Simone de Beauvoir",
      "name_ar": "سيمون دي بوفوار",
      "school_en": "Existentialism, Feminism",
      "school_ar": "الوجودية، النسوية",
      "era_en": "20th century",
      "era_ar": "القرن العشرين",
      "image": "https://upload.wikimedia.org/wikipedia/commons/1/1d/Simone_de_Beauvoir_1967.jpg",
      "short_description_en": "A French writer, intellectual, existentialist philosopher, political activist, feminist and social theorist.",
      "short_description_ar": "كاتبة فرنسية، ومفكرة، وفيلسوفة وجودية، وناشطة سياسية، ونسوية، ومنظرة اجتماعية.",
      "birth": "1908",
      "death": "1986",
      "nationality_en": "French",
      "nationality_ar": "فرنسية",
      "long_article_en": "De Beauvoir's 'The Second Sex' is a foundational text of modern feminism. In it, she analyzed the oppression of women from an existentialist perspective, arguing that 'One is not born, but rather becomes, a woman.' She explored the ways in which women are socially constructed as the 'Other' in a male-dominated world.",
      "long_article_ar": "يُعتبر 'الجنس الثاني' لبوفوار نصًا تأسيسيًا للنسوية الحديثة. فيه، حللت اضطهاد النساء من منظور وجودي، مجادلة بأن 'المرء لا يولد امرأة، بل يصبح كذلك.' استكشفت الطرق التي يتم بها بناء النساء اجتماعيًا كـ 'الآخر' في عالم يسيطر عليه الذكور.",
      "philosophical_impact_en": "De Beauvoir's work had a profound impact on feminism and existentialism. She challenged traditional gender roles and helped to shape the discourse around gender identity, equality, and women's liberation.",
      "philosophical_impact_ar": "كان لعمل بوفوار تأثير عميق على النسوية والوجودية. لقد تحدت أدوار الجنسين التقليدية وساعدت في تشكيل الخطاب حول الهوية الجنسية والمساواة وتحرير المرأة."
    },
    {
      "name_en": "Michel Foucault",
      "name_ar": "ميشيل فوكو",
      "school_en": "Structuralism, Post-structuralism",
      "school_ar": "البنيوية، ما بعد البنيوية",
      "era_en": "20th century",
      "era_ar": "القرن العشرون",
      "image": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Michel_Foucault_1975_2.jpg",
      "short_description_en": "A French philosopher, historian of ideas, social theorist, and literary critic.",
      "short_description_ar": "فيلسوف فرنسي، ومؤرخ للأفكار، ومنظر اجتماعي، وناقد أدبي.",
      "birth": "1926",
      "death": "1984",
      "nationality_en": "French",
      "nationality_ar": "فرنسي",
      "long_article_en": "Foucault's work focused on the relationship between power and knowledge, and how social institutions use power to control and define individuals. His books, such as 'Discipline and Punish' and 'The History of Sexuality,' examined the history of prisons, medicine, and sexuality to show how power operates in subtle and pervasive ways.",
      "long_article_ar": "ركز عمل فوكو على العلاقة بين السلطة والمعرفة، وكيف تستخدم المؤسسات الاجتماعية السلطة للسيطرة على الأفراد وتحديدهم. درست كتبه، مثل 'المراقبة والمعاقبة' و'تاريخ الجنسانية'، تاريخ السجون والطب والجنسانية لتظهر كيف تعمل السلطة بطرق خفية ومنتشرة.",
      "philosophical_impact_en": "Foucault's ideas on power, knowledge, and discourse have been extremely influential in a wide range of fields, including sociology, political science, literary criticism, and queer theory. He is a key figure in post-structuralism and postmodernism.",
      "philosophical_impact_ar": "كانت أفكار فوكو حول السلطة والمعرفة والخطاب مؤثرة للغاية في مجموعة واسعة من المجالات، بما في ذلك علم الاجتماع، والعلوم السياسية، والنقد الأدبي، والنظرية الكويرية. هو شخصية رئيسية في ما بعد البنيوية وما بعد الحداثة."
    },
    {
      "name_en": "Karl Marx",
      "name_ar": "كارل ماركس",
      "school_en": "Marxism",
      "school_ar": "الماركسية",
      "era_en": "19th century",
      "era_ar": "القرن التاسع عشر",
      "image": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Karl_Marx_001.jpg",
      "short_description_en": "A German philosopher, economist, historian, political theorist, sociologist, journalist, and revolutionary socialist.",
      "short_description_ar": "فيلسوف ألماني، واقتصادي، ومؤرخ، ومنظر سياسي، وعالم اجتماع، وصحفي، واشتراكي ثوري.",
      "birth": "1818",
      "death": "1883",
      "nationality_en": "German",
      "nationality_ar": "ألماني",
      "long_article_en": "Marx's philosophy is a form of dialectical and historical materialism. His most famous works, 'The Communist Manifesto' and 'Das Kapital,' argue that societies develop through class struggle. He predicted that capitalism would be overthrown by a proletarian revolution, leading to a classless communist society.",
      "long_article_ar": "فلسفة ماركس هي شكل من أشكال المادية الجدلية والتاريخية. يجادل في أشهر أعماله، 'البيان الشيوعي' و'رأس المال'، بأن المجتمعات تتطور من خلال الصراع الطبقي. توقع أن يتم الإطاحة بالرأسمالية بثورة بروليتارية، مما يؤدي إلى مجتمع شيوعي بلا طبقات.",
      "philosophical_impact_en": "Marxism has had a profound impact on political thought, economics, and social theory. It led to the formation of numerous political movements and states, and its concepts like class struggle and alienation are still central to critical theory.",
      "philosophical_impact_ar": "كان للماركسية تأثير عميق على الفكر السياسي والاقتصاد والنظرية الاجتماعية. أدت إلى تشكيل العديد من الحركات السياسية والدول، ولا تزال مفاهيمها مثل الصراع الطبقي والاغتراب محورية في النظرية النقدية."
    },
    {
      "name_en": "Confucius",
      "name_ar": "كونفوشيوس",
      "school_en": "Confucianism",
      "school_ar": "الكونفوشيوسية",
      "era_en": "Classical antiquity",
      "era_ar": "العصور الكلاسيكية القديمة",
      "image": "https://upload.wikimedia.org/wikipedia/commons/7/77/Confucius_c.1770.jpg",
      "short_description_en": "A Chinese philosopher and politician whose philosophy became the basis for Confucianism.",
      "short_description_ar": "فيلسوف وسياسي صيني أصبحت فلسفته أساسًا للكونفوشيوسية.",
      "birth": "-551",
      "death": "-479",
      "nationality_en": "Chinese",
      "nationality_ar": "صيني",
      "long_article_en": "Confucius's philosophy emphasized personal and governmental morality, correctness of social relationships, justice, kindness, and sincerity. He believed in the importance of education and self-cultivation. His teachings, preserved in the 'Analects,' focus on the concept of 'ren' (humaneness) and 'li' (ritual and propriety).",
      "long_article_ar": "أكدت فلسفة كونفوشيوس على الأخلاق الشخصية والحكومية، وصحة العلاقات الاجتماعية، والعدالة، واللطف، والإخلاص. آمن بأهمية التعليم وتنمية الذات. تركز تعاليمه، المحفوظة في 'مختارات كونفوشيوس'، على مفهوم 'الرن' (الإنسانية) و'اللي' (الطقوس واللياقة).",
      "philosophical_impact_en": "Confucianism has had a profound influence on Chinese and East Asian culture, politics, and social thought for over two millennia. It shaped the civil service examination system and remains a key component of East Asian values.",
      "philosophical_impact_ar": "كان للكونفوشيوسية تأثير عميق على الثقافة والسياسة والفكر الاجتماعي الصيني والشرق آسيوي لأكثر من ألفي عام. لقد شكلت نظام الامتحانات المدنية ولا تزال مكونًا رئيسيًا للقيم في شرق آسيا."
    },
    {
      "name_en": "Laozi",
      "name_ar": "لاوزي",
      "school_en": "Taoism",
      "school_ar": "التاوية",
      "era_en": "Classical antiquity",
      "era_ar": "العصور الكلاسيكية القديمة",
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Laozi_%28Lao_Tzu%29_by_Unkown.jpeg/1200px-Laozi_%28Lao_Tzu%29_by_Unkown.jpeg",
      "short_description_en": "An ancient Chinese philosopher and writer, and the central figure of Taoism.",
      "short_description_ar": "فيلسوف وكاتب صيني قديم، والشخصية المركزية للتاوية.",
      "birth": "6th century BC (approx.)",
      "death": "unknown",
      "nationality_en": "Chinese",
      "nationality_ar": "صيني",
      "long_article_en": "Laozi is credited with writing the 'Tao Te Ching,' a foundational text of Taoism. The philosophy of Taoism emphasizes living in harmony with the 'Tao' (the Way), a natural and universal principle. It advocates for humility, simplicity, and 'wu wei' (effortless action).",
      "long_article_ar": "يُنسب إلى لاوزي كتابة 'تاو تي تشينغ'، وهو نص تأسيسي للتاوية. تؤكد فلسفة التاوية على العيش في وئام مع 'التاو' (الطريق)، وهو مبدأ طبيعي وعالمي. تدعو إلى التواضع والبساطة و'وو وي' (الفعل بلا جهد).",
      "philosophical_impact_en": "Taoism, along with Confucianism and Buddhism, has had a profound and lasting impact on Chinese culture, philosophy, and religion. Its concepts of balance, nature, and spontaneity continue to influence art, medicine, and spirituality.",
      "philosophical_impact_ar": "كان للتاوية، جنبًا إلى جنب مع الكونفوشيوسية والبوذية، تأثير عميق ودائم على الثقافة والفلسفة والدين الصينيين. لا تزال مفاهيمها عن التوازن والطبيعة والعفوية تؤثر على الفن والطب والروحانية."
    },
    {
      "name_en": "Mary Wollstonecraft",
      "name_ar": "ماري وولستونكرافت",
      "school_en": "Feminism, Liberalism",
      "school_ar": "النسوية، الليبرالية",
      "era_en": "Enlightenment",
      "era_ar": "عصر التنوير",
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Mary_Wollstonecraft_by_John_Opie_%28c._1797%29.jpg/800px-Mary_Wollstonecraft_by_John_Opie_%28c._1797%29.jpg",
      "short_description_en": "An English writer, philosopher, and advocate of women's rights.",
      "short_description_ar": "كاتبة وفيلسوفة إنجليزية، ومدافعة عن حقوق المرأة.",
      "birth": "1759",
      "death": "1797",
      "nationality_en": "English",
      "nationality_ar": "إنجليزية",
      "long_article_en": "Wollstonecraft's 'A Vindication of the Rights of Woman' is one of the earliest works of feminist philosophy. She argued that women are not naturally inferior to men, but appear to be so because they lack education. She advocated for a society based on reason and for equal educational opportunities for women.",
      "long_article_ar": "يُعد 'دفاع عن حقوق المرأة' لوولستونكرافت أحد أقدم أعمال الفلسفة النسوية. جادلت بأن النساء لسن أدنى من الرجال بطبيعتهن، ولكنهن يظهرن كذلك لأنهن يفتقرن إلى التعليم. دعت إلى مجتمع قائم على العقل وإلى فرص تعليمية متساوية للنساء.",
      "philosophical_impact_en": "Wollstonecraft is considered a foundational figure of feminist philosophy. Her ideas on gender equality and education laid the groundwork for the feminist movements of the 19th and 20th centuries.",
      "philosophical_impact_ar": "تُعتبر وولستونكرافت شخصية تأسيسية في الفلسفة النسوية. أرست أفكارها حول المساواة بين الجنسين والتعليم الأساس للحركات النسوية في القرنين التاسع عشر والعشرين."
    },
    {
      "name_en": "Søren Kierkegaard",
      "name_ar": "سورين كيركجارد",
      "school_en": "Existentialism",
      "school_ar": "الوجودية",
      "era_en": "19th century",
      "era_ar": "القرن التاسع عشر",
      "image": "https://upload.wikimedia.org/wikipedia/commons/e/ec/S%C3%B8ren_Kierkegaard_1840.jpg",
      "short_description_en": "A Danish philosopher, theologian, poet, social critic, and religious author.",
      "short_description_ar": "فيلسوف دنماركي، ولاهوتي، وشاعر، وناقد اجتماعي، ومؤلف ديني.",
      "birth": "1813",
      "death": "1855",
      "nationality_en": "Danish",
      "nationality_ar": "دنماركي",
      "long_article_en": "Kierkegaard is widely regarded as the 'Father of Existentialism.' His work focused on the individual's subjective experience, the importance of choice, and the concepts of dread, despair, and faith. He critiqued the shallowness of modern life and the institutionalization of religion.",
      "long_article_ar": "يُعتبر كيركجارد على نطاق واسع 'أبو الوجودية'. ركز عمله على التجربة الذاتية للفرد، وأهمية الاختيار، ومفاهيم الخوف واليأس والإيمان. انتقد سطحية الحياة الحديثة ومأسسة الدين.",
      "philosophical_impact_en": "Kierkegaard's emphasis on the individual's responsibility to create meaning and the nature of subjective truth had a profound influence on existentialist thinkers like Jean-Paul Sartre and Albert Camus.",
      "philosophical_impact_ar": "كان لتركيز كيركجارد على مسؤولية الفرد في خلق المعنى وطبيعة الحقيقة الذاتية تأثير عميق على المفكرين الوجوديين مثل جان بول سارتر وألبير كامو."
    },
    {
      "name_en": "Hannah Arendt",
      "name_ar": "هانا أرندت",
      "school_en": "Political philosophy",
      "school_ar": "الفلسفة السياسية",
      "era_en": "20th century",
      "era_ar": "القرن العشرون",
      "image": "https://upload.wikimedia.org/wikipedia/commons/d/d1/Hannah_Arendt_portrait_by_Fred_Stein_1944.jpg",
      "short_description_en": "A German-born American political theorist and philosopher.",
      "short_description_ar": "منظرة سياسية وفيلسوفة أمريكية من أصل ألماني.",
      "birth": "1906",
      "death": "1975",
      "nationality_en": "German-American",
      "nationality_ar": "ألمانية-أمريكية",
      "long_article_en": "Arendt's work focused on the nature of totalitarianism, evil, and the public sphere. Her most famous work, 'The Origins of Totalitarianism,' examined the historical roots of Nazism and Stalinism. She also introduced the concept of the 'banality of evil' in her analysis of the trial of Adolf Eichmann.",
      "long_article_ar": "ركز عمل أرندت على طبيعة الشمولية والشر والمجال العام. أشهر أعمالها، 'أصول الشمولية'، درست الجذور التاريخية للنازية والستالينية. كما قدمت مفهوم 'تفاهة الشر' في تحليلها لمحاكمة أدولف أيخمان.",
      "philosophical_impact_en": "Arendt's analysis of power, politics, and human action has been highly influential in political science, history, and philosophy. She is considered one of the most important political thinkers of the 20th century.",
      "philosophical_impact_ar": "كان تحليل أرندت للسلطة والسياسة والفعل الإنساني مؤثرًا للغاية في العلوم السياسية والتاريخ والفلسفة. تُعتبر واحدة من أهم المفكرين السياسيين في القرن العشرين."
    },
    {
      "name_en": "Adam Smith",
      "name_ar": "آدم سميث",
      "school_en": "Classical economics",
      "school_ar": "الاقتصاد الكلاسيكي",
      "era_en": "Enlightenment",
      "era_ar": "عصر التنوير",
      "image": "https://upload.wikimedia.org/wikipedia/commons/f/f6/Adam_Smith_by_John_Kay%2C_1790.jpg",
      "short_description_en": "A Scottish economist and philosopher, and a key figure in the Scottish Enlightenment.",
      "short_description_ar": "اقتصادي وفيلسوف اسكتلندي، وشخصية رئيسية في عصر التنوير الاسكتلندي.",
      "birth": "1723",
      "death": "1790",
      "nationality_en": "Scottish",
      "nationality_ar": "اسكتلندي",
      "long_article_en": "Smith's 'The Wealth of Nations' is considered the first modern work of economics. He argued for free markets and the 'invisible hand' of the market, where individual self-interest leads to the collective good. He also wrote 'The Theory of Moral Sentiments,' a work on ethics and moral philosophy.",
      "long_article_ar": "يُعتبر 'ثروة الأمم' لسميث أول عمل حديث في الاقتصاد. جادل فيه بالأسواق الحرة و'اليد الخفية' للسوق، حيث تؤدي المصلحة الذاتية الفردية إلى الصالح العام. كما كتب 'نظرية المشاعر الأخلاقية'، وهو عمل حول الأخلاق والفلسفة الأخلاقية.",
      "philosophical_impact_en": "Smith's ideas on free markets and capitalism laid the foundation for modern economics. His work on moral philosophy also had a significant impact on ethical theory.",
      "philosophical_impact_ar": "أرست أفكار سميث حول الأسواق الحرة والرأسمالية الأساس للاقتصاد الحديث. كان لعمله في الفلسفة الأخلاقية أيضًا تأثير كبير على النظرية الأخلاقية."
    },
    {
      "name_en": "Avicenna (Ibn Sina)",
      "name_ar": "ابن سينا",
      "school_en": "Avicennism (Islamic philosophy)",
      "school_ar": "الفلسفة المشائية (الفلسفة الإسلامية)",
      "era_en": "Islamic Golden Age",
      "era_ar": "العصر الذهبي الإسلامي",
      "image": "https://upload.wikimedia.org/wikipedia/commons/e/e4/Avicenna_%28Ibn_Sina%29_by_Unkown.jpg",
      "short_description_en": "A Persian polymath who is regarded as one of the most significant thinkers and physicians of the Islamic Golden Age.",
      "short_description_ar": "موسوعي فارسي يُعتبر أحد أهم المفكرين والأطباء في العصر الذهبي الإسلامي.",
      "birth": "c. 980",
      "death": "1037",
      "nationality_en": "Persian",
      "nationality_ar": "فارسي",
      "long_article_en": "Avicenna's philosophy was a synthesis of Aristotelian and Neoplatonic thought, reconciled with Islamic theology. His 'Book of Healing' is a comprehensive philosophical and scientific encyclopedia. He made major contributions to logic, ethics, and metaphysics, and his 'Canon of Medicine' was a standard medical text for centuries.",
      "long_article_ar": "كانت فلسفة ابن سينا توليفًا للفكر الأرسطي والأفلوطيني، وتم التوفيق بينها وبين اللاهوت الإسلامي. يُعد 'كتاب الشفاء' له موسوعة فلسفية وعلمية شاملة. قدم مساهمات كبيرة في المنطق والأخلاق والميتافيزيقا، وكان 'القانون في الطب' نصًا طبيًا قياسيًا لقرون.",
      "philosophical_impact_en": "Avicenna's work had a profound influence on both Islamic and Western philosophy. His logical system and his concepts of being and essence were adopted by scholastic philosophers like Thomas Aquinas, and he is considered a pivotal figure in the history of medicine.",
      "philosophical_impact_ar": "كان لعمل ابن سينا تأثير عميق على الفلسفة الإسلامية والغربية على حد سواء. تم تبني نظامه المنطقي ومفاهيمه عن الوجود والجوهر من قبل الفلاسفة المدرسيين مثل توما الأكويني، ويعتبر شخصية محورية في تاريخ الطب."
    },
    {
      "name_en": "Averroes (Ibn Rushd)",
      "name_ar": "ابن رشد",
      "school_en": "Averroism (Islamic philosophy)",
      "school_ar": "الرشدية (الفلسفة الإسلامية)",
      "era_en": "Islamic Golden Age",
      "era_ar": "العصر الذهبي الإسلامي",
      "image": "https://upload.wikimedia.org/wikipedia/commons/a/ad/Averroes_by_Unkown.jpg",
      "short_description_en": "An Andalusian polymath and jurist who wrote on philosophy, theology, medicine, astronomy, and physics.",
      "short_description_ar": "موسوعي وفقيه أندلسي كتب في الفلسفة واللاهوت والطب والفلك والفيزياء.",
      "birth": "1126",
      "death": "1198",
      "nationality_en": "Andalusian",
      "nationality_ar": "أندلسي",
      "long_article_en": "Averroes was a leading commentator on Aristotle. He argued for the importance of reason and the harmony between philosophy and religion. His works, particularly 'The Incoherence of the Incoherence,' were a direct response to al-Ghazali's critique of philosophy.",
      "long_article_ar": "كان ابن رشد معلقًا رائدًا على أرسطو. جادل بأهمية العقل والتناغم بين الفلسفة والدين. كانت أعماله، وخاصة 'تهافت التهافت'، ردًا مباشرًا على نقد الغزالي للفلسفة.",
      "philosophical_impact_en": "Averroes had a major influence on Western European philosophy through his commentaries on Aristotle, which were widely translated and studied. His ideas on the intellect and the relationship between faith and reason were central to scholastic philosophy and the development of Western secularism.",
      "philosophical_impact_ar": "كان لابن رشد تأثير كبير على الفلسفة الأوروبية الغربية من خلال تعليقاته على أرسطو، التي تُرجمت ودُرست على نطاق واسع. كانت أفكاره حول العقل والعلاقة بين الإيمان والعقل محورية في الفلسفة المدرسية وتطور العلمانية الغربية."
    },
    {
      "name_en": "Al-Ghazali",
      "name_ar": "أبو حامد الغزالي",
      "school_en": "Ash'ari (Islamic theology), Sufism",
      "school_ar": "الأشعرية (اللاهوت الإسلامي)، الصوفية",
      "era_en": "Islamic Golden Age",
      "era_ar": "العصر الذهبي الإسلامي",
      "image": "https://upload.wikimedia.org/wikipedia/commons/1/13/Al-Ghazali_by_Unkown.jpg",
      "short_description_en": "A Persian polymath, jurist, theologian, logician, and mystic.",
      "short_description_ar": "موسوعي فارسي، فقيه، وعالم لاهوت، ومنطقي، وصوفي.",
      "birth": "c. 1058",
      "death": "1111",
      "nationality_en": "Persian",
      "nationality_ar": "فارسي",
      "long_article_en": "Al-Ghazali is a major figure in Islamic philosophy and theology. His work 'The Incoherence of the Philosophers' was a powerful critique of the falsafa (Islamic Aristotelianism), particularly the ideas of Avicenna and al-Farabi. He argued that reason alone could not lead to absolute truth and that a direct, mystical experience of God was necessary.",
      "long_article_ar": "يُعد الغزالي شخصية رئيسية في الفلسفة واللاهوت الإسلاميين. كان عمله 'تهافت الفلاسفة' نقدًا قويًا للفلسفة (الأرسطية الإسلامية)، وخاصة أفكار ابن سينا والفارابي. جادل بأن العقل وحده لا يمكن أن يؤدي إلى الحقيقة المطلقة وأن التجربة المباشرة والصوفية لله ضرورية.",
      "philosophical_impact_en": "Al-Ghazali's critique of philosophy was a major turning point in Islamic intellectual history, contributing to the decline of rationalist philosophy in the Islamic world. His synthesis of Sufism and orthodox theology had a lasting impact on Islamic thought.",
      "philosophical_impact_ar": "كان نقد الغزالي للفلسفة نقطة تحول رئيسية في التاريخ الفكري الإسلامي، مما ساهم في تراجع الفلسفة العقلانية في العالم الإسلامي. كان لتوليفه للصوفية واللاهوت الأرثوذكسي تأثير دائم على الفكر الإسلامي."
    },
    {
      "name_en": "Ibn Khaldun",
      "name_ar": "ابن خلدون",
      "school_en": "Social philosophy, Historiography",
      "school_ar": "الفلسفة الاجتماعية، التأريخ",
      "era_en": "Islamic Golden Age",
      "era_ar": "العصر الذهبي الإسلامي",
      "image": "https://upload.wikimedia.org/wikipedia/commons/a/a2/Ibn_Khaldun_by_Unkown.jpg",
      "short_description_en": "An Arab historian, philosopher, and social theorist from North Africa.",
      "short_description_ar": "مؤرخ وفيلسوف ومنظر اجتماعي عربي من شمال أفريقيا.",
      "birth": "1332",
      "death": "1406",
      "nationality_en": "Tunisian",
      "nationality_ar": "تونسي",
      "long_article_en": "Ibn Khaldun is considered a precursor to modern sociology, historiography, and economics. His most famous work, 'The Muqaddimah,' laid out his theories on the rise and fall of civilizations. He introduced the concept of 'asabiyyah' (group solidarity) as a key factor in social cohesion and political power.",
      "long_article_ar": "يُعتبر ابن خلدون رائدًا لعلم الاجتماع الحديث، والتأريخ، والاقتصاد. عمله الأكثر شهرة، 'المقدمة'، طرح نظرياته حول صعود وسقوط الحضارات. قدم مفهوم 'العصبية' (التضامن الجماعي) كعامل رئيسي في التماسك الاجتماعي والسلطة السياسية.",
      "philosophical_impact_en": "Ibn Khaldun's work was revolutionary in its use of empirical and systematic analysis to study history and society. He is widely considered one of the greatest thinkers of the Middle Ages and a founding father of several modern disciplines.",
      "philosophical_impact_ar": "كان عمل ابن خلدون ثوريًا في استخدامه للتحليل التجريبي والمنهجي لدراسة التاريخ والمجتمع. يُعتبر على نطاق واسع أحد أعظم المفكرين في العصور الوسطى وأبًا مؤسسًا لعدة تخصصات حديثة."
    },
    {
      "name_en": "Al-Farabi",
      "name_ar": "الفارابي",
      "school_en": "Islamic philosophy, Neoplatonism",
      "school_ar": "الفلسفة الإسلامية، الأفلوطينية الجديدة",
      "era_en": "Islamic Golden Age",
      "era_ar": "العصر الذهبي الإسلامي",
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Al-Farabi.jpg/800px-Al-Farabi.jpg",
      "short_description_en": "A a Turkic-origin scholar and philosopher, widely regarded as the 'Second Teacher' after Aristotle.",
      "short_description_ar": "عالم وفيلسوف من أصل تركي، يُعتبر على نطاق واسع 'المعلم الثاني' بعد أرسطو.",
      "birth": "c. 872",
      "death": "950",
      "nationality_en": "Turkic",
      "nationality_ar": "تركي",
      "long_article_en": "Al-Farabi was a major figure in the early Islamic philosophical tradition. He sought to create a synthesis of the philosophies of Plato and Aristotle, and his work on logic and political philosophy was highly influential. His 'On the Principles of the Opinions of the Inhabitants of the Virtuous City' outlined his vision for an ideal society based on philosophical principles.",
      "long_article_ar": "كان الفارابي شخصية رئيسية في التقليد الفلسفي الإسلامي المبكر. سعى إلى خلق توليف بين فلسفتي أفلاطون وأرسطو، وكان لعمله في المنطق والفلسفة السياسية تأثير كبير. حدد في 'آراء أهل المدينة الفاضلة' رؤيته لمجتمع مثالي قائم على المبادئ الفلسفية.",
      "philosophical_impact_en": "Al-Farabi's work was a crucial link in the transmission of Greek philosophy to the Islamic and Western worlds. His commentaries on Aristotle and his political philosophy influenced later thinkers like Avicenna and Maimonides.",
      "philosophical_impact_ar": "كان عمل الفارابي حلقة وصل حاسمة في نقل الفلسفة اليونانية إلى العالمين الإسلامي والغربي. أثرت تعليقاته على أرسطو وفلسفته السياسية على مفكرين لاحقين مثل ابن سينا وموسى بن ميمون."
    },
    {
      "name_en": "Maimonides (Moses ben Maimon)",
      "name_ar": "موسى بن ميمون",
      "school_en": "Jewish philosophy, Aristotelianism",
      "school_ar": "الفلسفة اليهودية، الأرسطية",
      "era_en": "Medieval period",
      "era_ar": "العصور الوسطى",
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Maimonides_by_Unkown.jpg/800px-Maimonides_by_Unkown.jpg",
      "short_description_en": "A Sephardic Jewish philosopher, astronomer, and physician.",
      "short_description_ar": "فيلسوف يهودي سفاردي، وفلكي، وطبيب.",
      "birth": "c. 1135",
      "death": "1204",
      "nationality_en": "Spanish-Jewish",
      "nationality_ar": "إسباني-يهودي",
      "long_article_en": "Maimonides sought to reconcile Aristotelian philosophy with Jewish theology. His most famous work, 'The Guide for the Perplexed,' provided a philosophical interpretation of Jewish law and belief. He argued that there was no conflict between faith and reason and that both were paths to knowledge of God.",
      "long_article_ar": "سعى موسى بن ميمون إلى التوفيق بين الفلسفة الأرسطية واللاهوت اليهودي. عمله الأكثر شهرة، 'دلالة الحائرين'، قدم تفسيرًا فلسفيًا للشريعة والمعتقد اليهودي. جادل بأنه لا يوجد تعارض بين الإيمان والعقل وأن كلاهما طريق لمعرفة الله.",
      "philosophical_impact_en": "Maimonides is one of the most influential Jewish thinkers of all time. His work had a profound impact on Jewish philosophy and also influenced Christian scholastic philosophers, including Thomas Aquinas.",
      "philosophical_impact_ar": "يُعتبر موسى بن ميمون أحد أكثر المفكرين اليهود تأثيرًا على الإطلاق. كان لعمله تأثير عميق على الفلسفة اليهودية وأثر أيضًا على الفلاسفة المدرسيين المسيحيين، بما في ذلك توما الأكويني."
    },
    {
      "name_en": "Friedrich Engels",
      "name_ar": "فريدريش إنجلز",
      "school_en": "Marxism",
      "school_ar": "الماركسية",
      "era_en": "19th century",
      "era_ar": "القرن التاسع عشر",
      "image": "https://upload.wikimedia.org/wikipedia/commons/b/b8/Engels_1891_cropped.jpg",
      "short_description_en": "A German social scientist, author, political theorist, and philosopher, who developed communist theory alongside Karl Marx.",
      "short_description_ar": "عالم اجتماع ألماني، ومؤلف، ومنظر سياسي، وفيلسوف، طور النظرية الشيوعية جنبًا إلى جنب مع كارل ماركس.",
      "birth": "1820",
      "death": "1895",
      "nationality_en": "German",
      "nationality_ar": "ألماني",
      "long_article_en": "Engels was a key collaborator of Karl Marx, co-writing 'The Communist Manifesto.' After Marx's death, he edited and published the remaining volumes of 'Das Kapital.' His work 'The Origin of the Family, Private Property, and the State' applied historical materialism to the study of social and family structures.",
      "long_article_ar": "كان إنجلز متعاونًا رئيسيًا مع كارل ماركس، حيث شارك في كتابة 'البيان الشيوعي'. بعد وفاة ماركس، قام بتحرير ونشر المجلدات المتبقية من 'رأس المال'. عمله 'أصل العائلة والملكية الخاصة والدولة' طبق المادية التاريخية على دراسة الهياكل الاجتماعية والأسرية.",
      "philosophical_impact_en": "Engels's contributions were crucial in the development and popularization of Marxist theory. His work helped to shape the philosophical and political foundations of communism.",
      "philosophical_impact_ar": "كانت مساهمات إنجلز حاسمة في تطوير ونشر النظرية الماركسية. ساعد عمله في تشكيل الأسس الفلسفية والسياسية للشيوعية."
    },
    {
      "name_en": "Sigmund Freud",
      "name_ar": "سيغموند فرويد",
      "school_en": "Psychoanalysis",
      "school_ar": "التحليل النفسي",
      "era_en": "19th-20th century",
      "era_ar": "القرن التاسع عشر-العشرون",
      "image": "https://upload.wikimedia.org/wikipedia/commons/1/12/Sigmund_Freud_by_Max_Halberstadt_%28cropped%29.jpg",
      "short_description_en": "An Austrian neurologist and the founder of psychoanalysis.",
      "short_description_ar": "طبيب أعصاب نمساوي ومؤسس التحليل النفسي.",
      "birth": "1856",
      "death": "1939",
      "nationality_en": "Austrian",
      "nationality_ar": "نمساوي",
      "long_article_en": "Freud's work revolutionized the understanding of the human mind. He posited that the unconscious mind contains repressed thoughts and desires that influence behavior. He developed techniques such as dream analysis and free association to access the unconscious and treat psychological disorders.",
      "long_article_ar": "ثورة أعمال فرويد في فهم العقل البشري. افترض أن العقل الباطن يحتوي على أفكار ورغبات مكبوتة تؤثر على السلوك. طور تقنيات مثل تحليل الأحلام والتداعي الحر للوصول إلى العقل الباطن وعلاج الاضطرابات النفسية.",
      "philosophical_impact_en": "Freud's theories had a profound impact on psychology, philosophy, and Western culture. His ideas on the unconscious, the Oedipus complex, and the stages of psychosexual development have been highly influential, even if they are often debated and revised.",
      "philosophical_impact_ar": "كان لنظريات فرويد تأثير عميق على علم النفس والفلسفة والثقافة الغربية. كانت أفكاره حول اللاوعي، وعقدة أوديب، ومراحل التطور النفسي الجنسي مؤثرة للغاية، حتى لو كانت غالبًا ما تكون موضع نقاش ومراجعة."
    },
    {
      "name_en": "Ludwig Wittgenstein",
      "name_ar": "لودفيج فيتجنشتاين",
      "school_en": "Analytic philosophy",
      "school_ar": "الفلسفة التحليلية",
      "era_en": "20th century",
      "era_ar": "القرن العشرون",
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Ludwig_Wittgenstein.jpg/800px-Ludwig_Wittgenstein.jpg",
      "short_description_en": "An Austrian-British philosopher who worked primarily in logic, the philosophy of mathematics, the philosophy of mind, and the philosophy of language.",
      "short_description_ar": "فيلسوف نمساوي-بريطاني عمل بشكل أساسي في المنطق، وفلسفة الرياضيات، وفلسفة العقل، وفلسفة اللغة.",
      "birth": "1889",
      "death": "1951",
      "nationality_en": "Austrian-British",
      "nationality_ar": "نمساوي-بريطاني",
      "long_article_en": "Wittgenstein's work is often divided into two main periods. In his early 'Tractatus Logico-Philosophicus,' he argued that language is a picture of reality. In his later 'Philosophical Investigations,' he rejected this view, arguing that the meaning of words is found in their use, a concept known as 'language games.'",
      "long_article_ar": "يُقسم عمل فيتجنشتاين غالبًا إلى فترتين رئيسيتين. في عمله المبكر 'رسالة منطقية فلسفية'، جادل بأن اللغة هي صورة للواقع. في عمله اللاحق 'تحقيقات فلسفية'، رفض هذا الرأي، مجادلًا بأن معنى الكلمات يوجد في استخدامها، وهو مفهوم يُعرف باسم 'ألعاب اللغة'.",
      "philosophical_impact_en": "Wittgenstein's philosophy had a profound impact on analytic philosophy and the philosophy of language. His later work, in particular, has been influential in fields ranging from ethics to anthropology.",
      "philosophical_impact_ar": "كان لفلسفة فيتجنشتاين تأثير عميق على الفلسفة التحليلية وفلسفة اللغة. كان لعمله اللاحق، على وجه الخصوص، تأثير في مجالات تتراوح من الأخلاق إلى الأنثروبولوجيا."
    },
    {
      "name_en": "Jean-Paul Sartre",
      "name_ar": "جان بول سارتر",
      "school_en": "Existentialism, Marxism",
      "school_ar": "الوجودية، الماركسية",
      "era_en": "20th century",
      "era_ar": "القرن العشرون",
      "image": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Jean-Paul_Sartre_1967_by_Elsa_Triolet.jpg",
      "short_description_en": "A French existentialist philosopher, playwright, novelist, screenwriter, political activist, biographer, and literary critic.",
      "short_description_ar": "فيلسوف وجودي فرنسي، وكاتب مسرحي، وروائي، وكاتب سيناريو، وناشط سياسي، وكاتب سيرة ذاتية، وناقد أدبي.",
      "birth": "1905",
      "death": "1980",
      "nationality_en": "French",
      "nationality_ar": "فرنسي",
      "long_article_en": "Sartre's philosophy is encapsulated in the phrase 'existence precedes essence.' He argued that there is no pre-given human nature and that individuals are radically free and responsible for creating their own meaning in a meaningless world. His major works include 'Being and Nothingness' and 'Existentialism is a Humanism.'",
      "long_article_ar": "تتلخص فلسفة سارتر في عبارة 'الوجود يسبق الجوهر'. جادل بأنه لا توجد طبيعة بشرية معطاة مسبقًا وأن الأفراد أحرار بشكل جذري ومسؤولون عن خلق معناهم الخاص في عالم بلا معنى. تشمل أعماله الرئيسية 'الوجود والعدم' و'الوجودية مذهب إنساني'.",
      "philosophical_impact_en": "Sartre was the leading figure of 20th-century French existentialism. His ideas had a profound impact on literature, psychology, and politics, and he helped to popularize existentialist concepts like freedom, responsibility, and angst.",
      "philosophical_impact_ar": "كان سارتر الشخصية الرائدة في الوجودية الفرنسية في القرن العشرين. كان لأفكاره تأثير عميق على الأدب وعلم النفس والسياسة، وساعد في نشر المفاهيم الوجودية مثل الحرية والمسؤولية والقلق."
    },
    {
      "name_en": "Voltaire",
      "name_ar": "فولتير",
      "school_en": "Enlightenment",
      "school_ar": "عصر التنوير",
      "era_en": "Early modern period",
      "era_ar": "العصر الحديث المبكر",
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Voltaire_by_Maurice_Quentin_de_La_Tour.jpg/800px-Voltaire_by_Maurice_Quentin_de_La_Tour.jpg",
      "short_description_en": "A French Enlightenment writer, historian, and philosopher famous for his wit and his advocacy of freedom of speech, freedom of religion, and separation of church and state.",
      "short_description_ar": "كاتب ومؤرخ وفيلسوف فرنسي من عصر التنوير، اشتهر بذكائه ودفاعه عن حرية التعبير، وحرية الدين، وفصل الكنيسة عن الدولة.",
      "birth": "1694",
      "death": "1778",
      "nationality_en": "French",
      "nationality_ar": "فرنسي",
      "long_article_en": "Voltaire's work was a relentless critique of religious intolerance, censorship, and superstition. He wrote in a variety of literary forms, including essays, novels, and plays. His satirical novella 'Candide' is a famous critique of philosophical optimism and the problem of evil.",
      "long_article_ar": "كان عمل فولتير نقدًا لا هوادة فيه للتعصب الديني والرقابة والخرافات. كتب في مجموعة متنوعة من الأشكال الأدبية، بما في ذلك المقالات والروايات والمسرحيات. روايته الساخرة 'كانديد' هي نقد شهير للتفاؤل الفلسفي ومشكلة الشر.",
      "philosophical_impact_en": "Voltaire's ideas were central to the Enlightenment and had a significant impact on the American and French Revolutions. His advocacy for civil liberties and social reform has had a lasting legacy on modern democratic societies.",
      "philosophical_impact_ar": "كانت أفكار فولتير محورية في عصر التنوير وكان لها تأثير كبير على الثورتين الأمريكية والفرنسية. كان لدفاعه عن الحريات المدنية والإصلاح الاجتماعي إرث دائم على المجتمعات الديمقراطية الحديثة."
    },
    {
      "name_en": "Noam Chomsky",
      "name_ar": "نعوم تشومسكي",
      "school_en": "Analytic philosophy",
      "school_ar": "الفلسفة التحليلية",
      "era_en": "20th-21st century",
      "era_ar": "القرن العشرون-الحادي والعشرون",
      "image": "https://upload.wikimedia.org/wikipedia/commons/b/b2/Noam_Chomsky_2011.jpg",
      "short_description_en": "An American linguist, philosopher, cognitive scientist, and political activist.",
      "short_description_ar": "لغوي أمريكي، وفيلسوف، وعالم معرفي، وناشط سياسي.",
      "birth": "1928",
      "death": "present",
      "nationality_en": "American",
      "nationality_ar": "أمريكي",
      "long_article_en": "Chomsky is a major figure in analytic philosophy and linguistics. In linguistics, he developed the theory of generative grammar, which posits that language is an innate human faculty. As a political activist, he is known for his critique of US foreign policy and global capitalism.",
      "long_article_ar": "تشومسكي شخصية رئيسية في الفلسفة التحليلية واللغويات. في اللغويات، طور نظرية النحو التوليدي، التي تفترض أن اللغة هي قدرة بشرية فطرية. كناشط سياسي، يُعرف بنقده للسياسة الخارجية الأمريكية والرأسمالية العالمية.",
      "philosophical_impact_en": "Chomsky's work in linguistics fundamentally changed the field and sparked the 'cognitive revolution.' His political writings and activism have made him a leading voice in left-wing politics and a major critic of power.",
      "philosophical_impact_ar": "غير عمل تشومسكي في اللغويات المجال بشكل جذري وأطلق 'الثورة المعرفية'. كتاباته ونشاطه السياسي جعلته صوتًا رائدًا في السياسة اليسارية وناقدًا رئيسيًا للسلطة."
    },
    {
      "name_en": "Friedrich von Hayek",
      "name_ar": "فريدريش فون هايك",
      "school_en": "Austrian School of economics, Liberalism",
      "school_ar": "المدرسة النمساوية للاقتصاد، الليبرالية",
      "era_en": "20th century",
      "era_ar": "القرن العشرون",
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Friedrich_Hayek.jpg/800px-Friedrich_Hayek.jpg",
      "short_description_en": "An Austrian-British economist and philosopher best known for his defense of classical liberalism.",
      "short_description_ar": "اقتصادي وفيلسوف نمساوي-بريطاني اشتهر بدفاعه عن الليبرالية الكلاسيكية.",
      "birth": "1899",
      "death": "1992",
      "nationality_en": "Austrian-British",
      "nationality_ar": "نمساوي-بريطاني",
      "long_article_en": "Hayek's work 'The Road to Serfdom' argued that central planning and socialism inevitably lead to totalitarianism. He was a strong advocate for free markets and limited government, arguing that the dispersed knowledge in a society makes central economic planning impossible and inefficient.",
      "long_article_ar": "جادل عمل هايك 'الطريق إلى العبودية' بأن التخطيط المركزي والاشتراكية يؤديان حتمًا إلى الشمولية. كان مدافعًا قويًا عن الأسواق الحرة والحكومة المحدودة، مجادلًا بأن المعرفة المبعثرة في المجتمع تجعل التخطيط الاقتصادي المركزي مستحيلاً وغير فعال.",
      "philosophical_impact_en": "Hayek was a key figure in the revival of classical liberalism and free-market economics in the 20th century. His ideas were highly influential on conservative political movements and continue to shape debates about the role of the state in the economy.",
      "philosophical_impact_ar": "كان هايك شخصية رئيسية في إحياء الليبرالية الكلاسيكية واقتصاديات السوق الحرة في القرن العشرين. كانت أفكاره مؤثرة للغاية على الحركات السياسية المحافظة ولا تزال تشكل النقاشات حول دور الدولة في الاقتصاد."
    },
    {
      "name_en": "Ayn Rand",
      "name_ar": "آين راند",
      "school_en": "Objectivism",
      "school_ar": "الموضوعية",
      "era_en": "20th century",
      "era_ar": "القرن العشرون",
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Ayn_Rand_-_November_1957.jpg/800px-Ayn_Rand_-_November_1957.jpg",
      "short_description_en": "A Russian-American writer and philosopher, known for developing the philosophical system of Objectivism.",
      "short_description_ar": "كاتبة وفيلسوفة روسية-أمريكية، معروفة بتطوير النظام الفلسفي للموضوعية.",
      "birth": "1905",
      "death": "1982",
      "nationality_en": "Russian-American",
      "nationality_ar": "روسية-أمريكية",
      "long_article_en": "Ayn Rand's Objectivism holds that reality exists independently of consciousness, that human beings gain knowledge through reason, that the proper moral purpose of one's life is the pursuit of one's own rational self-interest, and that the only social system consistent with this morality is laissez-faire capitalism. Her novels, such as 'The Fountainhead' and 'Atlas Shrugged,' are used to illustrate her philosophical ideas.",
      "long_article_ar": "تقول موضوعية آين راند إن الواقع موجود بشكل مستقل عن الوعي، وأن البشر يكتسبون المعرفة من خلال العقل، وأن الغاية الأخلاقية الصحيحة لحياة المرء هي السعي وراء مصلحته الذاتية العقلانية، وأن النظام الاجتماعي الوحيد المتوافق مع هذه الأخلاق هو الرأسمالية القائمة على مبدأ عدم التدخل. تُستخدم رواياتها، مثل 'المنبع' و'أطلس يهزأ'، لتوضيح أفكارها الفلسفية.",
      "philosophical_impact_en": "Rand's philosophy of Objectivism has had a significant influence on libertarian and conservative political thought in the United States, although it is often rejected by academic philosophers.",
      "philosophical_impact_ar": "كان لفلسفة راند الموضوعية تأثير كبير على الفكر السياسي الليبرتاري والمحافظ في الولايات المتحدة، على الرغم من أنها غالبًا ما تُرفض من قبل الفلاسفة الأكاديميين."
    },
    {
      "name_en": "Diogenes of Sinope",
      "name_ar": "ديوجين الكلبي",
      "school_en": "Cynicism",
      "school_ar": "الكلبية",
      "era_en": "Classical antiquity",
      "era_ar": "العصور الكلاسيكية القديمة",
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Diogenes-Statue-Sinope.jpg/800px-Diogenes-Statue-Sinope.jpg",
      "short_description_en": "A Greek philosopher and one of the founders of Cynic philosophy.",
      "short_description_ar": "فيلسوف يوناني وأحد مؤسسي الفلسفة الكلبية.",
      "birth": "c. 412 BC",
      "death": "c. 323 BC",
      "nationality_en": "Greek",
      "nationality_ar": "يوناني",
      "long_article_en": "Diogenes was known for his radical rejection of social conventions and his ascetic lifestyle. He lived in a large ceramic jar in Athens and famously carried a lamp in daylight, claiming to be 'looking for an honest man.' His philosophy emphasized self-sufficiency, simplicity, and living in accordance with nature.",
      "long_article_ar": "كان ديوجين معروفًا برفضه الجذري للتقاليد الاجتماعية وأسلوب حياته الزاهد. عاش في جرة خزفية كبيرة في أثينا وحمل مصباحًا في وضح النهار، مدعيًا أنه 'يبحث عن رجل صادق'. أكدت فلسفته على الاكتفاء الذاتي والبساطة والعيش وفقًا للطبيعة.",
      "philosophical_impact_en": "Diogenes and the Cynics had a profound influence on later philosophical schools, including Stoicism. His example of living a life of radical freedom and virtue outside of societal norms has been an inspiration for many.",
      "philosophical_impact_ar": "كان لديوجين والكلبيين تأثير عميق على المدارس الفلسفية اللاحقة، بما في ذلك الرواقية. كان مثاله في عيش حياة من الحرية الجذرية والفضيلة خارج الأعراف الاجتماعية مصدر إلهام للكثيرين."
    },
    {
      "name_en": "Epictetus",
      "name_ar": "إبكتيتوس",
      "school_en": "Stoicism",
      "school_ar": "الرواقية",
      "era_en": "Classical antiquity",
      "era_ar": "العصور الكلاسيكية القديمة",
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Epictetus_-_Roman_copy_of_a_lost_Greek_original.jpg/800px-Epictetus_-_Roman_copy_of_a_lost_Greek_original.jpg",
      "short_description_en": "A Greek Stoic philosopher who lived in Rome.",
      "short_description_ar": "فيلسوف رواقي يوناني عاش في روما.",
      "birth": "c. 50 AD",
      "death": "c. 135 AD",
      "nationality_en": "Roman (Greek)",
      "nationality_ar": "روماني (يوناني)",
      "long_article_en": "Epictetus taught that philosophy is a way of life and not just a theoretical discipline. His teachings, recorded by his student Arrian in the 'Discourses' and the 'Enchiridion,' focused on what is within our power (our thoughts, judgments, and desires) and what is not (external events). He taught that the key to a good life is to focus on what you can control and accept what you cannot.",
      "long_article_ar": "علم إبكتيتوس أن الفلسفة هي طريقة حياة وليست مجرد تخصص نظري. ركزت تعاليمه، التي سجلها تلميذه أريانوس في 'المحاورات' و'الكتيب'، على ما هو في سلطتنا (أفكارنا وأحكامنا ورغباتنا) وما ليس كذلك (الأحداث الخارجية). علم أن مفتاح الحياة الجيدة هو التركيز على ما يمكنك التحكم فيه وقبول ما لا يمكنك.",
      "philosophical_impact_en": "Epictetus's teachings on self-control, resilience, and inner peace have had a lasting impact on Western thought and are a central part of Stoic philosophy. His work continues to be a source of practical wisdom and guidance.",
      "philosophical_impact_ar": "كان لتعاليم إبكتيتوس حول ضبط النفس والمرونة والسلام الداخلي تأثير دائم على الفكر الغربي وهي جزء أساسي من الفلسفة الرواقية. لا يزال عمله مصدرًا للحكمة العملية والإرشاد."
    },
    {
      "name_en": "Seneca the Younger",
      "name_ar": "سينيكا الأصغر",
      "school_en": "Stoicism",
      "school_ar": "الرواقية",
      "era_en": "Classical antiquity",
      "era_ar": "العصور الكلاسيكية القديمة",
      "image": "https://upload.wikimedia.org/wikipedia/commons/e/ec/Seneca_the_Younger.jpg",
      "short_description_en": "A Roman Stoic philosopher, statesman, dramatist, and a leading figure in the Roman imperial period.",
      "short_description_ar": "فيلسوف رواقي روماني، ورجل دولة، وكاتب مسرحي، وشخصية رائدة في العصر الإمبراطوري الروماني.",
      "birth": "c. 4 BC",
      "death": "65 AD",
      "nationality_en": "Roman",
      "nationality_ar": "روماني",
      "long_article_en": "Seneca's philosophical works, including his 'Letters from a Stoic' and 'On the Shortness of Life,' provide practical advice on how to live a virtuous life. He wrote about topics such as anger, grief, and the pursuit of happiness, emphasizing the importance of reason, self-control, and resilience in the face of adversity.",
      "long_article_ar": "تقدم أعمال سينيكا الفلسفية، بما في ذلك 'رسائل من رواقي' و'عن قصر الحياة'، نصائح عملية حول كيفية عيش حياة فاضلة. كتب عن مواضيع مثل الغضب، والحزن، والسعي وراء السعادة، مؤكدًا على أهمية العقل، وضبط النفس، والمرونة في مواجهة الشدائد.",
      "philosophical_impact_en": "Seneca is a major figure in Stoic philosophy and has been a source of inspiration for many throughout history. His emphasis on practical ethics and his eloquent writing style made Stoicism accessible to a wider audience, and his influence can be seen in later Christian and Renaissance thought.",
      "philosophical_impact_ar": "يُعد سينيكا شخصية رئيسية في الفلسفة الرواقية وكان مصدر إلهام للكثيرين عبر التاريخ. تركيزه على الأخلاق العملية وأسلوبه البليغ في الكتابة جعل الفلسفة الرواقية متاحة لجمهور أوسع، ويمكن رؤية تأثيره في الفكر المسيحي وعصر النهضة اللاحق."
    },
    {
      "name_en": "Marcus Aurelius",
      "name_ar": "ماركوس أوريليوس",
      "school_en": "Stoicism",
      "school_ar": "الرواقية",
      "era_en": "Classical antiquity",
      "era_ar": "العصور الكلاسيكية القديمة",
      "image": "https://upload.wikimedia.org/wikipedia/commons/e/ee/Bust_of_Marcus_Aurelius_at_the_Capitoline_Museums_in_Rome.jpg",
      "short_description_en": "A Roman emperor and a Stoic philosopher.",
      "short_description_ar": "إمبراطور روماني وفيلسوف رواقي.",
      "birth": "121 AD",
      "death": "180 AD",
      "nationality_en": "Roman",
      "nationality_ar": "روماني",
      "long_article_en": "Marcus Aurelius's 'Meditations' is a series of personal reflections and notes on his Stoic philosophy. It is a guide to living a life of virtue and reason, even in the face of suffering and death. He wrote about topics such as the impermanence of things, the importance of living in the present, and the need to accept what we cannot control.",
      "long_article_ar": "تُعد 'تأملات' ماركوس أوريليوس سلسلة من التأملات الشخصية والملاحظات حول فلسفته الرواقية. إنها دليل لعيش حياة من الفضيلة والعقل، حتى في مواجهة المعاناة والموت. كتب عن مواضيع مثل زوال الأشياء، وأهمية العيش في الحاضر، والحاجة إلى قبول ما لا يمكننا التحكم فيه.",
      "philosophical_impact_en": "Marcus Aurelius's 'Meditations' is a timeless classic of philosophical literature. His work has been a source of inspiration for generations, and his teachings on resilience, self-discipline, and inner peace are still relevant today.",
      "philosophical_impact_ar": "تُعد 'تأملات' ماركوس أوريليوس كلاسيكية خالدة في الأدب الفلسفي. كان عمله مصدر إلهام لأجيال، ولا تزال تعاليمه حول المرونة، والانضباط الذاتي، والسلام الداخلي ذات صلة حتى اليوم."
    },
    {
      "name_en": "Epicurus",
      "name_ar": "أبيقور",
      "school_en": "Epicureanism",
      "school_ar": "الأبيقورية",
      "era_en": "Classical antiquity",
      "era_ar": "العصور الكلاسيكية القديمة",
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Epicurus_Louvre_Ma_140.jpg/800px-Epicurus_Louvre_Ma_140.jpg",
      "short_description_en": "A Greek philosopher and the founder of the school of philosophy called Epicureanism.",
      "short_description_ar": "فيلسوف يوناني ومؤسس المدرسة الفلسفية المسماة الأبيقورية.",
      "birth": "c. 341 BC",
      "death": "c. 270 BC",
      "nationality_en": "Greek",
      "nationality_ar": "يوناني",
      "long_article_en": "Epicurus taught that the goal of life is to achieve a state of 'ataraxia' (tranquility and freedom from fear) and 'aponia' (absence of pain). He argued that happiness is achieved through a simple life, surrounded by friends, and by avoiding unnecessary desires and fears, especially the fear of death and the gods.",
      "long_article_ar": "علم أبيقور أن هدف الحياة هو تحقيق حالة من 'الأتاراكسيا' (السكينة والتحرر من الخوف) و'الأبونيا' (غياب الألم). جادل بأن السعادة تتحقق من خلال حياة بسيطة، محاطة بالأصدقاء، وبتجنب الرغبات والمخاوف غير الضرورية، وخاصة الخوف من الموت والآلهة.",
      "philosophical_impact_en": "Epicureanism had a significant influence in the Hellenistic and Roman periods. Its emphasis on pleasure as the highest good, understood as a state of tranquility rather than sensual gratification, has had a lasting impact on ethical thought.",
      "philosophical_impact_ar": "كان للأبيقورية تأثير كبير في الفترتين الهلنستية والرومانية. تركيزها على اللذة كأعلى خير، والتي تُفهم على أنها حالة من السكينة بدلاً من الإشباع الحسي، كان له تأثير دائم على الفكر الأخلاقي."
    },
    {
      "name_en": "Plotinus",
      "name_ar": "أفلوطين",
      "school_en": "Neoplatonism",
      "school_ar": "الأفلوطينية الجديدة",
      "era_en": "Classical antiquity",
      "era_ar": "العصور الكلاسيكية القديمة",
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Plotinus.jpg/800px-Plotinus.jpg",
      "short_description_en": "A Hellenistic philosopher and a major figure in the development of Neoplatonism.",
      "short_description_ar": "فيلسوف هلنستي وشخصية رئيسية في تطور الأفلوطينية الجديدة.",
      "birth": "c. 204 AD",
      "death": "c. 270 AD",
      "nationality_en": "Egyptian-Roman (Greek)",
      "nationality_ar": "مصري-روماني (يوناني)",
      "long_article_en": "Plotinus's philosophy is based on a metaphysics of a hierarchy of being, emanating from the 'One' or 'The Good.' He posited that the universe emanates from the One in a series of stages, including the Intellect and the Soul. The goal of human life, he argued, is to return to the One through intellectual and spiritual contemplation.",
      "long_article_ar": "تعتمد فلسفة أفلوطين على ميتافيزيقا تسلسل هرمي للوجود، ينبثق من 'الواحد' أو 'الخير'. افترض أن الكون ينبثق من الواحد في سلسلة من المراحل، بما في ذلك العقل والروح. جادل بأن هدف الحياة البشرية هو العودة إلى الواحد من خلال التأمل الفكري والروحي.",
      "philosophical_impact_en": "Plotinus is considered the founder of Neoplatonism, a major philosophical school that influenced later Christian, Jewish, and Islamic philosophy. His ideas on emanation, the soul, and the One had a profound impact on religious and mystical thought.",
      "philosophical_impact_ar": "يُعتبر أفلوطين مؤسس الأفلوطينية الجديدة، وهي مدرسة فلسفية رئيسية أثرت على الفلسفة المسيحية واليهودية والإسلامية اللاحقة. كان لأفكاره حول الانبثاق، والروح، والواحد تأثير عميق على الفكر الديني والصوفي."
    }];
  

  const handleInsertPhilosophers = async () => {
    const { data, error } = await supabase.from("philosophers").insert(philosophers);
  
    if (error) {
      console.error("Error inserting philosopher:", error);
    } else {
      console.log("Philosopher inserted successfully:", data);
    }
  };
  const handleGetPhilosophers = async () => {
    const { data, error } = await supabase.from("philosophers").select("*");
    console.log(data);
  };
  const article =[ {
    title: {
      en: "The Future of Artificial Intelligence",
      ar: "المستقبل التكنولوجي الذكاء الاصطناعي"
    },  
    description: {
      en: "Explain the future of Artificial Intelligence and how it will change the world",
      ar: "شرح المستقبل التكنولوجي الذكاء الاصطناعي وكيف سيتغير العالم"
    },
    content: {
      en: "It will be the most important technology in the future and how it will change the world",
      ar: "سيكون أكثر التكنولوجيات الأهمية في المستقبل وكيف سيتغير العالم"
    },
    author_name: {
      en: "Socrates",
      ar: "سقراط"
    },
    author_field: {
      en: "Philosopher",
      ar: "فيلسوف"
    },
    author_avatar: "https://upload.wikimedia.org/wikipedia/commons/d/d2/Head_Sokrates_Glyptothek_Munich.jpg",
    category: {
      en: "Philosophy",
      ar: "فلسفة"
    },
    date: {
      en: "2025-01-01",
      ar: "2025-01-01"
    },
    likes: 100,
    dislikes: 10,
  },
  {
    title: {
      en: "The Future of Artificial Intelligence",
      ar: "المستقبل التكنولوجي الذكاء الاصطناعي"
    },
    description: {
      en: "Explain the future of Artificial Intelligence and how it will change the world",
      ar: "شرح المستقبل التكنولوجي الذكاء الاصطناعي وكيف سيتغير العالم"
    },
    content: {
      en: "It will be the most important technology in the future and how it will change the world",
      ar: "سيكون أكثر التكنولوجيات الأهمية في المستقبل وكيف سيتغير العالم"
    },
    author_name: {
      en: "Socrates",
      ar: "سقراط"
    },
    author_field: {
      en: "Philosopher",
      ar: "فيلسوف"
    },
    author_avatar: "https://upload.wikimedia.org/wikipedia/commons/d/d2/Head_Sokrates_Glyptothek_Munich.jpg",
      category: {
      en: "Philosophy",
      ar: "فلسفة"
    },
    date: {
      en: "2025-01-01",
      ar: "2025-01-01"
    },
    likes: 100,
    dislikes: 10,
  }
]


  return (
    <div className="articles">
      {article.map((article) => (
        <ArticlesCard article={article} />
      ))}
     
    </div>
  );
};

export default Articles;
